### ISSUE TITLE
Proposed App Architecture

### ISSUE THREAD

**Issue by adamlawrencium** [adamalawrence/Ostia#7]
## Overview

**(1) DataHub**: Basically all the data from the exchange servers can be fed into something called a DataHub - where we store all relevant information any strategy would need about currency pairs. Indicators can either be stored here, or calculated upon a strategy's request (might affect efficiency).

**(2) Strategies**: The data from DataHub can be called by any strategy. Originally I was thinking about using Websockets to emit all the data, then have the strategies open up listeners based on what data they want. @BirchellE helped me realize that we can just call the all exchange objects since Node keeps everything live and updated. 

**(3) TradingHub**: The strategies then send all their orders to our TradingHub, which contains exchange API wrappers/interfaces. The TradingHub then sends those requests out to the relevant exchanges.

**Possible issues:**
- Standardizing exchange data to a universal format that can be used by any strategy.
- Inefficiencies calculating trading indicators that aren't being used (might be fixable by having strategies calculate them instead).
- Redundancies involved with creating API wrappers in TradingHub, when API framework might already be available in DataHub.

Overall, I think this architecture provides clean boundaries between our distinct components (modularity), and will allow us to add a backtesting feature or plug-in any exchange or strategy (extensibility) we or a user might need.

![ostia archit-2](https://cloud.githubusercontent.com/assets/10917080/19633785/257c62b0-9983-11e6-9f58-b5b841b7df94.png)

**Comment by Mingling94** [comment]
1. We need to break this into a client server model doe. A person's computer can only run constantly if on a desktop and even then it's not ideal. 
2. What is the symbol in upper right of DataHub and TradingHub mean?
3. Don't name an object type "Exchange", too redundant in our naming scheme. Doesn't DataHub == Exchange here anyway?
4. `OrderBook.currencyPair` should be two [JS enums](http://stackoverflow.com/questions/287903/enums-in-javascript) variables for explicit-ness.
5. Are orderbooks ordered by time? Is a list the ideal structure?
6. Lol 30DayAvg let's not have a variable with a number first.
7. 
   > Redundancies involved with creating API wrappers in TradingHub, when API framework might already be available in DataHub.

Let me throw this idea at you. Because API calls have to be made with the least possible code "distance" so as to minimize errors at this level since it's a really common occurrence, we have the TradingHub cover all API needs and be a dependency within DataHub (and rename them differently cuz then they aren't that related horizontally anymore).

Now since Strategies and DataHub require different API calls (e.g. DataHub should never be able to make a "buy" call), the exports of TradingHub with all the API wrappers is a factory function that, given a [JS enum](http://stackoverflow.com/questions/287903/enums-in-javascript) (same link as above) exports an object with ONLY THE NEEDED CALLS. Obviously Strategies will have access to a larger portion (perhaps even a super-set) of DataHub's API calls.

Otherwise looks good, I can tell you put a lot of thought into this!

**Comment by adamlawrencium** [comment]
Sweet, thanks for the feedback. Addressing your points:
1. Which components do you think should be part of the server and client? Similar to what you said, a client should be able to run their strategies whether or not they're at their computer. Therefore, I'd say all the components the strategies _**need**_ to run should be part of the server -- to me those components look like DataHub, Strategies, and TradingHub.
2. That's a UML symbol for a generic 'component'.
3. DataHub should hold all the exchanges. Each exchange will hold their currency pair order books and other information. Where would the redundancy occur?
4. Got it. Some exchanges return their pairs as "BTC_ETH". So we'd have to split on the '_'.
5. The Orderbook won't be like the Maps of bids and asks we have now. They will contain additional information.  Exchange --> [Orderbook, Orderbook, ...] --> {pair: "BTC_ETH, bids: [...], asks: [...], indicators, etc..}. But if this is still confusing then maybe we should change it.
6. Placeholder:) This [repo for technical analysis](https://github.com/andredumas/techan.js/tree/master/src/indicator) has some examples.

Oo, that sounds like a very smooth solution -  I'll work that into the next iteration!

**Comment by Mingling94** [comment]
1. Okay yeah that makes sense.
2. Missing for Strategies box was why I asked.
3. Oh DataHub to Exchange is a 1-to-many. I just now got that.
4. Ah so each orderbook in an exchange is differentiated by currency pair. Then it seems like they should be stored in a js {} object and use the currency pairs as keys.

**Comment by BirchellE** [comment]
So most of my discussion has been with Adam (I'll try to do that in these comments from now on), but I'd like to say that the whole accessing subsets of data is definitely a great idea. That way there doesn't have to be one single data set that everything is accessing. I'm excited to start putting this plan into action!

**Comment by adamlawrencium** [comment]
Here's a second version that includes @Mingling94's suggestion:
I tried to balance showing the class hierarchy with TradingHub <-- DataHub, while making things look pretty

![ostia archit v2](https://cloud.githubusercontent.com/assets/10917080/19668084/2a5f90ea-9a23-11e6-933a-e497c4f56df8.png)

**Comment by Mingling94** [comment]
I don't think DataHub should extend TradingHub. Although it will use its methods, it should just hold an instance of TradingHub, whose purpose is completely different than DataHub's. How about we name them Exchanges and Wrappers? Similar to how we named Strategies?
